services:
  - type: web
    name: charonboat
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn charonboat.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: charonboat
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
